### ISSUE TITLE
Crash when starting

### ISSUE THREAD

**Issue by lautriva** [LordOfDragons/democap#3]
Hi, 
To start, thanks you for providing mocap for free 🙂

My plan is to use it with Blender to make animations

When starting, the application progress bar goes to 99%, then crash (See images below)

Thanks in advance

OS : Linux Mint 22.1
CPU: Intel i9-10900K 
GPU : RTX 3080

Downloaded the [last version](https://github.com/LordOfDragons/democap/releases/tag/v1.3) of democap from releases and used it with [dragengine-live-1.25.2.zip](https://github.com/LordOfDragons/dragengine/releases/download/v1.25.2/dragengine-live-1.25.2.zip)

PS (not related) : Why do I have a `mod.io` folder created in my home folder?
I suggest it should be in another directory like `.config` (as other applications do) to avoid polluting the home folder and maybe also not created until I use mods

---

![Image](https://github.com/user-attachments/assets/b4b0e675-acf7-47ff-8c1d-48a6b127b45d)

![Image](https://github.com/user-attachments/assets/7c76762e-6a19-4735-bfae-97fc1226104e)

```bash
$ ./launchLinux64 
[LauncherLive] [2025-03-24 12:33:08] System config path: /home/lautriva/Tools/mocap/linux64/etc/delauncher
[LauncherLive] [2025-03-24 12:33:08] User config path: /home/lautriva/Tools/mocap/linux64/config/user/delauncher
[LauncherLive] [2025-03-24 12:33:08] Shares path: /home/lautriva/Tools/mocap/linux64/share/delauncher
[LauncherLive] [2025-03-24 12:33:08] Games path: /home/lautriva/Tools/mocap
[LauncherLive] [2025-03-24 12:33:08] Logs path: /home/lautriva/Tools/mocap/logs
[LauncherLive] [2025-03-24 12:33:08] EngineProcess.StartEngine: Create OS Unix
[LauncherLive] [2025-03-24 12:33:08] Processing LoadModules
Shutdown handler: initialize.
[LauncherLive] [2025-03-24 12:33:08] Processing GetProperty(property=0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetProperty(property=1)
[LauncherLive] [2025-03-24 12:33:08] Processing GetProperty(property=2)
[LauncherLive] [2025-03-24 12:33:08] Processing GetProperty(property=3)
[LauncherLive] [2025-03-24 12:33:08] Engine config path = '/home/lautriva/Tools/mocap/linux64/etc/dragengine'
[LauncherLive] [2025-03-24 12:33:08] Engine share path = '/home/lautriva/Tools/mocap/linux64/share/dragengine'
[LauncherLive] [2025-03-24 12:33:08] Engine lib path = '/home/lautriva/Tools/mocap/linux64/lib/dragengine'
[LauncherLive] [2025-03-24 12:33:08] Processing GetDisplayCurrentResolution(display=0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetDisplayResolutions(display=0, resolutions=0, resolutionCount=0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetDisplayResolutions(display=0, resolutions=1, resolutionCount=16)
[LauncherLive] [2025-03-24 12:33:08] Processing GetDisplayCurrentScaleFactor(display=0)
[LauncherLive] [2025-03-24 12:33:08] loading module list
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/crashrecovery/basicrecovery/1.10/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/crashrecovery/simplyquit/1.10/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/graphic/opengl/1.25/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/graphic/null/1.0/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/input/xsystem/1.24/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/input/console/1.0/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/physics/bullet/1.21/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/audio/openal/1.25/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/audio/null/1.0/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/network/basic/1.24/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/scripting/dragonscript/1.25/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/animator/deanimator/1.21/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/ai/deai/1.19/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/synthesizer/desynthesizer/1.3/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/vr/openvr/1.17/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/vr/openxr/1.23/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/vr/null/1.17/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/archive/delga/1.16/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/animation/deanim/1.17/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/animation/fbxanim/1.20/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/font/defont/1.0/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/image/tga/1.0/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/image/jpeg/1.0/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/image/png/1.0/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/image/webp3d/1.22/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/image/ies/1.4/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/image/webp/1.22/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/image/png3d/1.16/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/model/demodel/1.17/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/model/fbxmodel/1.20/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/rig/fbxrig/1.20/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/rig/derig/1.18/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/skin/deskin/1.18/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/skin/fbxskin/1.20/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/langpack/delangpack/1.16/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/sound/oggvorbis/1.0/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/video/apng/1.17/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/video/theora/1.17/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/video/webm/1.17/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/occlusionmesh/deocclusionmesh/1.0/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/service/eossdk/1.23/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/service/steamsdk/1.23/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Reading module definition from '/engine/lib/modules/service/modio/1.23/module.xml'
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='BasicRecovery':1.10)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='BasicRecovery')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='SimplyQuit':1.10)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='SimplyQuit')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='OpenGL':1.25)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='OpenGL')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='NullGraphic':1.0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='NullGraphic')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='XSystemInput':1.24)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='XSystemInput')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='ConsoleInput':1.0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='ConsoleInput')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='Bullet':1.21)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='Bullet')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='OpenAL':1.25)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='OpenAL')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='NullAudio':1.0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='NullAudio')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='BasicNetwork':1.24)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='BasicNetwork')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DragonScript':1.25)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DragonScript')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DEAnimator':1.21)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DEAnimator')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DEAI':1.19)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DEAI')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DESynthesizer':1.3)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DESynthesizer')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='OpenVR':1.17)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='OpenVR')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='OpenXR':1.23)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='OpenXR')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='NullVR':1.17)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='NullVR')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DELGA':1.16)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DELGA')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DEAnim':1.17)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DEAnim')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='FBXAnim':1.20)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='FBXAnim')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DEFont':1.0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DEFont')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='Targa':1.0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='Targa')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='JPEG':1.0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='JPEG')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='PNG':1.0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='PNG')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='WebP-3D':1.22)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='WebP-3D')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='IES':1.4)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='IES')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='WebP':1.22)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='WebP')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='PNG-3D':1.16)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='PNG-3D')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DEModel':1.17)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DEModel')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='FBXModel':1.20)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='FBXModel')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='FBXRig':1.20)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='FBXRig')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DERig':1.18)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DERig')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DESkin':1.18)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DESkin')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='FBXSkin':1.20)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='FBXSkin')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DELangPack':1.16)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DELangPack')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='OggVorbis':1.0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='OggVorbis')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='APNG':1.17)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='APNG')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='Theora':1.17)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='Theora')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='WebM':1.17)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='WebM')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='DEOcclusionMesh':1.0)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='DEOcclusionMesh')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='EosSdk':1.23)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='EosSdk')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='SteamSdk':1.23)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='SteamSdk')
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleStatus(module='Modio':1.23)
[LauncherLive] [2025-03-24 12:33:08] Processing GetModuleParamList(moduleName='Modio')
[LauncherLive] [2025-03-24 12:33:08] Engine configuration file not found, will be created upon exiting
[LauncherLive] [2025-03-24 12:33:08] Default profile: graphic module = 'OpenGL'
[LauncherLive] [2025-03-24 12:33:08] Default profile: input module = 'XSystemInput'
[LauncherLive] [2025-03-24 12:33:08] Default profile: physics module = 'Bullet'
[LauncherLive] [2025-03-24 12:33:08] Default profile: animator module = 'DEAnimator'
[LauncherLive] [2025-03-24 12:33:08] Default profile: ai module = 'DEAI'
[LauncherLive] [2025-03-24 12:33:08] Default profile: crash recovery module = 'BasicRecovery'
[LauncherLive] [2025-03-24 12:33:08] Default profile: audio module = 'OpenAL'
[LauncherLive] [2025-03-24 12:33:08] Default profile: synthesizer module = 'DESynthesizer'
[LauncherLive] [2025-03-24 12:33:08] Default profile: network module = 'BasicNetwork'
[LauncherLive] [2025-03-24 12:33:09] Default profile: VR module = 'OpenXR'
[LauncherLive] [2025-03-24 12:33:09] Loading game list
[LauncherLive] [2025-03-24 12:33:09] Reading game configuration file for ''
[LauncherLive] [2025-03-24 12:33:09] Reading game file '/home/lautriva/Tools/mocap/DEMoCap-1.3.delga'
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaGameDefs (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaFiles (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaFiles (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaFiles (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
[LauncherLive] [2025-03-24 12:33:09] Reading patch file '/home/lautriva/Tools/mocap/DEMoCap-1.3.delga'
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaPatchDefs (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
[LauncherLive] [2025-03-24 12:33:09] Reading game file '/home/lautriva/Tools/mocap/DEMoCap-1.3.delga'
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaGameDefs (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaFiles (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaFiles (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaFiles (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
[LauncherLive] [2025-03-24 12:33:09] Reading patch file '/home/lautriva/Tools/mocap/DEMoCap-1.3.delga'
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaPatchDefs (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
[LauncherLive] [2025-03-24 12:33:09] Loading patch list
[LauncherLive] [2025-03-24 12:33:09] Reading patch file '/home/lautriva/Tools/mocap/DEMoCap-1.3.delga'
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaPatchDefs (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
[LauncherLive] [2025-03-24 12:33:09] Reading patch file '/home/lautriva/Tools/mocap/DEMoCap-1.3.delga'
[LauncherLive] [2025-03-24 12:33:09] Processing ReadDelgaPatchDefs (delgaFile=/home/lautriva/Tools/mocap/DEMoCap-1.3.delga)
Shutdown handler: cleanup.
[LauncherLive] [2025-03-24 12:33:09] Reading game configuration file for 'DEMoCap'
[LiveLauncher] [2025-03-24 12:33:09] Cache application ID = 'e31f1c11-3ca6-c66b-adca-95484bedfc1f'
[LiveLauncher] [2025-03-24 12:33:09] Starting game 'DEMoCap' using profile ''
[LauncherLive] [2025-03-24 12:33:09] Writing game configuration file for 'DEMoCap'
[LauncherLive] [2025-03-24 12:33:09] Starting game 'DEMoCap'
[LauncherLive] [2025-03-24 12:33:09] EngineProcess.StartEngine: Create OS Unix
[LauncherLive] [2025-03-24 12:33:09] Processing SetCacheAppID(id='e31f1c11-3ca6-c66b-adca-95484bedfc1f')
[LauncherLive] [2025-03-24 12:33:09] Processing LoadModules
Shutdown handler: initialize.
[LauncherLive] [2025-03-24 12:33:09] Processing ActivateModule(module='BasicRecovery':)
[LauncherLive] [2025-03-24 12:33:09] Processing ActivateModule(module='OpenGL':)
[LauncherLive] [2025-03-24 12:33:09] Processing ActivateModule(module='XSystemInput':)
[LauncherLive] [2025-03-24 12:33:09] Processing ActivateModule(module='Bullet':)
[LauncherLive] [2025-03-24 12:33:09] Processing ActivateModule(module='DEAnimator':)
[LauncherLive] [2025-03-24 12:33:09] Processing ActivateModule(module='DEAI':)
[LauncherLive] [2025-03-24 12:33:09] Processing ActivateModule(module='OpenAL':)
[LauncherLive] [2025-03-24 12:33:09] Processing ActivateModule(module='DESynthesizer':)
[LauncherLive] [2025-03-24 12:33:09] Processing ActivateModule(module='BasicNetwork':)
[LauncherLive] [2025-03-24 12:33:09] Processing ActivateModule(module='OpenXR':)
[LauncherLive] [2025-03-24 12:33:09] Processing ActivateModule(module='DragonScript':1.25)
[LauncherLive] [2025-03-24 12:33:09] Processing SetDataDir(directory='')
[LauncherLive] [2025-03-24 12:33:09] Processing SetCmdLineArgs(arguments='')
[LauncherLive] [2025-03-24 12:33:09] Processing VFSAddDelga(delgaFile='/home/lautriva/Tools/mocap/DEMoCap-1.3.delga', archivePath=, hiddenPath=0)
[LauncherLive] [2025-03-24 12:33:09] Processing VFSAddScriptSharedDataDir
[LauncherLive] [2025-03-24 12:33:09] Processing ModulesAddVFSContainers(stage='patches')
[LauncherLive] [2025-03-24 12:33:09] Processing ModulesAddVFSContainers(stage='mods')
[LauncherLive] [2025-03-24 12:33:09] Processing ModulesAddVFSContainers(stage='overlay')
[LauncherLive] [2025-03-24 12:33:09] Processing VFSAddDiskDir(vfsRoot='/',nativeDirectory='/home/lautriva/Tools/mocap/linux64/config/user/delauncher/games/e31f1c11-3ca6-c66b-adca-95484bedfc1f/overlay',readOnly=n,hiddenPath=0)
[LauncherLive] [2025-03-24 12:33:09] Processing SetPathOverlay(path='/home/lautriva/Tools/mocap/linux64/config/user/delauncher/games/e31f1c11-3ca6-c66b-adca-95484bedfc1f/overlay')
[LauncherLive] [2025-03-24 12:33:09] Processing VFSAddDiskDir(vfsRoot='/config',nativeDirectory='/home/lautriva/Tools/mocap/linux64/config/user/delauncher/games/e31f1c11-3ca6-c66b-adca-95484bedfc1f/config',readOnly=n,hiddenPath=0)
[LauncherLive] [2025-03-24 12:33:09] Processing SetPathConfig(path='/home/lautriva/Tools/mocap/linux64/config/user/delauncher/games/e31f1c11-3ca6-c66b-adca-95484bedfc1f/config')
[LauncherLive] [2025-03-24 12:33:09] Processing VFSAddDiskDir(vfsRoot='/capture',nativeDirectory='/home/lautriva/Tools/mocap/linux64/config/user/delauncher/games/e31f1c11-3ca6-c66b-adca-95484bedfc1f/capture',readOnly=n,hiddenPath=0)
[LauncherLive] [2025-03-24 12:33:09] Processing SetPathCapture(path='/home/lautriva/Tools/mocap/linux64/config/user/delauncher/games/e31f1c11-3ca6-c66b-adca-95484bedfc1f/capture')
[LauncherLive] [2025-03-24 12:33:09] Processing CreateRenderWindow(width=1280,height=800,fullScreen=n,windowTitle='DEMoCap',iconPath='/content/images/icon256.png')
[LauncherLive] [2025-03-24 12:33:09] Processing StartGame(scriptDirectory='/scripts' scriptVersion='1.25' gameObject='GameApp')
[LauncherLive] [2025-03-24 12:33:09] Game started
[11:33:15.669265715:669ms][Warning][File] Failed to load global configuration overrides: File not found
[11:33:15.740676644:740ms][Error][File] Error opening file: 2
[11:33:15.740685610:740ms][Error][File] Error code 20744 while trying to open /home/lautriva/mod.io/common/6907/metadata/state.json: Error reading file
Shutdown handler: cleanup.
```

**Comment by LordOfDragons** [comment]
Can you please provide (on pastebin for example) the log file ( ~/.config/delauncher/logs/games/e31f1c11-3ca6-c66b-adca-95484bedfc1f/logs/last_run.log )? The script should not have thrown an exception but the real error should be visible in the logs.

Concerning the "mod.io" directory this is created by the Mod.io service module when it is loaded. This is a foreign library I have no direct influence upon. I'll bring it up though with the Mod.io maintainers if this can be changed. I'm certain this is going to work out. I can also not postponed the creation of this directory until you use mods since the service module has to figure out first if you have mods installed or not. And the Mod.io library creates this directory already when it checks if you have mods installed or not. As mentioned I'll do my best to get them to move the directory or at last figure out a way to get it moved by the game engine.

**Comment by lautriva** [comment]
The log was not in the folder you provided but instead in the folder `logs/games/e31f1c11-3ca6-c66b-adca-95484bedfc1f/logs` folder relative to the dragengine entry executable

The complete log is available [here](https://paste.hostux.net/?1d86dd1b09947e5b#HVAaTFtF3J8LyV7VRH3dwUkUmawioZm81dVMujD4ABUW) (expiring in 6 days)

Thanks for the explanation about mod.io, keep me updated

**Comment by LordOfDragons** [comment]
This is really strange. The logs show a division by zero but for a script location where there is a non-0 check. This should be impossible. Does this happen every time you run DEMoCap?

**Comment by lautriva** [comment]
> Does this happen every time you run DEMoCap?

yes, Every time

**Comment by LordOfDragons** [comment]
Can you try this nightly build with a small change? https://github.com/LordOfDragons/democap/releases/download/nightly/DEMoCap-nightly.delga .

**Comment by lautriva** [comment]
Still crashing 😢 
[logs](https://paste.hostux.net/?2f03883a84ee7749#933Z293JDitFKa3sddxNPqr5rGgNjfUGeBJQQFLsbY3Y) attached

**Comment by LordOfDragons** [comment]
So the problem is in the OpenGL graphic module. Unfortunately Github failed to include the debug symbols in the release build so I can't pinpoint what happens. I've modified the github build to fix the debug symbol problem. Please download https://github.com/LordOfDragons/dragengine/releases/download/nightly/dragengine-live-nightly.zip and paste the new logs. Then I should be able to pinpoint exactly where things go wrong.

**Comment by lautriva** [comment]
Not sure if normal, but this time no window appears, and no game log produced

Here is the [launcher.log](https://paste.hostux.net/?2738cb16a64fd1b7#7pfwg1THvjSCso7EScFXE3CBYFr4jpSAVyASnzPsFgSG)

**Comment by LordOfDragons** [comment]
Sorry, I made a mistake. I damaged the library checksums with the debug symbol adjustment. Please re-download the https://github.com/LordOfDragons/dragengine/releases/download/nightly/dragengine-live-nightly.zip . It should not properly start and give the right logs.

**Comment by lautriva** [comment]
ok, now it starts (and crash of course) 
Here is the [last_run.log](https://paste.hostux.net/?5008ae4d6e899aa4#9R1p4zLNQtdqQrikzi1Q2j5i54ceLkspjoxEriLQ1PgK)

**Comment by LordOfDragons** [comment]
Looks like somewhere some code manages to set the scaling of an element to 0. Not good. I'm not sure how this can happen so I've now hardened all placed where scaling could potentially be problematic. Try running https://github.com/LordOfDragons/democap/releases/download/nightly/DEMoCap-nightly.delga and see if it works better now.

**Comment by lautriva** [comment]
Still no luck :(

[last_run.log](https://paste.hostux.net/?e2b2fb34ca61f926#5fie86jXxH5T7zWDrrgdx2kWD6sdNhSMV8LR7LS4CCmr)

> Looks like somewhere some code manages to set the scaling of an element to 0. Not good. I'm not sure how this can happen

This may look like a memory corruption

**Comment by LordOfDragons** [comment]
If this would be a memory corruption it would be randomly (sometimes it works, sometimes not), especially after the changes I made. This div-by-zero really doesn't make any sense and it is the first time I see it like this (especially using the live-launcher).

Let's try something. Can you run something from https://github.com/LordOfDragons/deexamples/releases/tag/v1.25 , for example ExampleVR.delga ? I want to see if there is a general problem going on here or an application specific one.

EDIT: Also can you try deleting the user config directory of DEMoCap from <your-nightly-directory>/linux64/config/user/delauncher/games/e31f1c11-3ca6-c66b-adca-95484bedfc1f ? Just to make sure the first failed run did not manage to create a config/cache which is totally broken.

**Comment by lautriva** [comment]
Tested with the example app delga and I also have a crash ([log attached](https://paste.hostux.net/?d323b96766b3eda6#6Df8EUDqwUh7261jZsRSEPiEbsZ9Xkp5vbddq4eoCPGY))

Tested also with the Audio test and Graphic test delgas

Seems to be related to the engine and not with VR, so maybe you can try to reproduce it in a VM (Linux Mint 22 Xfce)

about your edit : In fact when I do tests, I remove all dragengine files between runs as I didn't know where the cache were stored so there cannot be "cache broken" artifacts remaining from the first failed run 🙂 

Edit : also the [log](https://paste.hostux.net/?65560c197147b933#BjW59wZ6hbMHEB6Rfjv6Kk8r9zRVjLf5NU1issLcP72d) with the debug live nightly build

**Comment by LordOfDragons** [comment]
Something is utterly wrong there since these exceptions are all over the place. I do not think this is a game engine problem but maybe a system or system library problem. I can try looking at this in a VM but this looks very strange. Maybe there is somewhere a broken library somewhere, I don't know.

**Comment by LordOfDragons** [comment]
I've now tried running it in a VM on an nVidia machine. Unfortunately this is not working since VirtualBox supports only OpenGL 4.1 in a VM and is missing important compute shader extensions so the game engine can not start.

I then tried running using a docker image from docker hub ( https://hub.docker.com/r/linuxmintd/mint22-amd64 ). This way I could run the game engine and run both DEMoCap and DEExampleApp without a problem. So technically it should be working. I'm not sure what goes on.

That said in your first image you had a black background and other problems. I've seen this so far only on nVidia laptops with nVidia. Their prime-system can use either nVidia GPU or Intel GPU to give high performance or low performance. And nVidia prime is notorious for running games with the Intel GPU or even worse start running the game with nVidia GPU (since starting has high GPU demand) and then while running suddenly switching to the Intel GPU (because the load is smaller now). This has the unholy effect of totally trashing OpenGL because resources are rug-pulled underneath the application. In the best case some OpenGL calls fail and the game fails and in the worst case it crashes. But I don't think you are using a laptop, right?

**Comment by lautriva** [comment]
you are right, I'm using a desktop and not laptop

I don't think I have nvidia prime

**Comment by LordOfDragons** [comment]
I have not figured out something so far but github made a huge update-blunder breaking things left and right. In the process of fixing this I had to also update some external libraries build into the game engine and it perhaps their blunder reached back in time and did bad things. I tested the new nightly I just build ( https://github.com/LordOfDragons/dragengine/releases/download/nightly/dragengine-live-nightly.zip ) against the Mint docker image and it works on my system. It's grasping for straws I guess but maybe you can test if the new nightly happens to work on your system?

**Comment by lautriva** [comment]
Tried this morning but still no luck... ([log](https://paste.hostux.net/?40328a4bca9844ea#6R7Wz4dnMu3jy4Vdwo98HbdoTLYknD1VpS9iiFv1dxeV))

**Comment by lautriva** [comment]
To not leave without giving you any clues about my problem, I can confirm that #4 is the same problem as this one

```
II [DragonScript] [2025-11-18 08:02:37] [Console] Failed loading game world '/content/worlds/default.deworld': Division by zero
1) Dragengine.Gui.ProgressGauge.createBlendColorMatrix(): 306
2) Dragengine.Gui.ProgressGauge.updateProgress(): 276
3) Dragengine.Gui.ProgressGauge.setBlendCanvasCreator(): 184
4) Dragengine.Gui.Designers.DefaultProgressGaugeDesigner.ProgressGaugeStateDesign.apply(): 167
5) Dragengine.Gui.Designers.DefaultWidgetDesigner.designWidget(): 430
6) Dragengine.Gui.Widget.<block>(): 2529
7) Dragengine.Gui.Widget.runWhileBlockingLayoutParent(): 350
8) Dragengine.Gui.Widget.runWhileBlockingLayoutParent(): 355
9) Dragengine.Gui.Widget.design(): 2528
10) Dragengine.Gui.Widget.setDesigner(): 851
11) Dragengine.Gui.Widget.onGuiThemeChanged(): 2492
12) Dragengine.Gui.ProgressGauge.onGuiThemeChanged(): 236
13) Dragengine.Gui.Container.<block>(): 950
14) Dragengine.Gui.Container.<block>(): 948
15) Dragengine.Gui.Container.runWhileBlockingLayout(): 252
16) Dragengine.Gui.Container.runWhileBlockingLayout(): 257
17) Dragengine.Gui.Container.onGuiThemeChanged(): 945
18) Dragengine.Gui.Container.<block>(): 950
19) Dragengine.Gui.Container.<block>(): 948
20) Dragengine.Gui.Container.runWhileBlockingLayout(): 252
21) Dragengine.Gui.Container.runWhileBlockingLayout(): 257
22) Dragengine.Gui.Container.onGuiThemeChanged(): 945
23) Dragengine.Gui.Container.<block>(): 950
24) Dragengine.Gui.Container.<block>(): 948
25) Dragengine.Gui.Container.runWhileBlockingLayout(): 252
26) Dragengine.Gui.Container.runWhileBlockingLayout(): 257
27) Dragengine.Gui.Container.onGuiThemeChanged(): 945
28) Dragengine.Gui.Container.<block>(): 950
29) Dragengine.Gui.Container.<block>(): 948
30) Dragengine.Gui.Container.runWhileBlockingLayout(): 252
31) Dragengine.Gui.Container.runWhileBlockingLayout(): 257
32) Dragengine.Gui.Container.onGuiThemeChanged(): 945
33) Dragengine.Gui.Window.onGuiThemeChanged(): 886
34) Dragengine.Gui.Widget.setParent(): 1311
35) Dragengine.Gui.Container.addWidget(): 328
36) Dragengine.Gui.Desktop.addWidget(): 665
37) Dragengine.Gui.Desktop.addWindow(): 656
38) Democap.StartGame.createLoadingWindow(): 172
39) Dragengine.Utils.GameWorldLoader.startLoading(): 361
EE [Modio] [2025-11-18 08:02:37] deModioService.pOnLogCallback: [07:02:37.339455226:339ms][Error][File] Error opening file: 2
EE [Modio] [2025-11-18 08:02:37] deModioService.pOnLogCallback: [07:02:37.339477575:339ms][Error][File] Error code 20744 while trying to open /home/myself/mod.io/common/6907/metadata/state.json: Error reading file
```

**Comment by LordOfDragons** [comment]
Can you also try the latest release? This would be DEMoCap 1.6 with Drag[en]gine 1.29 . See the post #4 about uninstalling all the files to make a clean start.

You can also try using the LiveLauncher. This way you do not have to install anything to test (and to rule out a problem with steam not installing properly). Download the live launcher from https://dragondreams.s3.eu-central-1.amazonaws.com/downloads/temporary/dragengine-live-1.29.zip then unpack it somewhere. Then download https://github.com/LordOfDragons/democap/releases/download/v1.6/DEMoCap-1.6.delga and place it next to "launch64" in that directory. Then run "launch64". This would rule out interference of steam.

**Comment by lautriva** [comment]
still not worked 😢 Got nearly same black screen as the [first image](https://github.com/LordOfDragons/democap/issues/3#issue-2942996279) of this issue + [logs](https://paste.hostux.net/?9aefcb47dfbe1365#FToJfANBJH9gYFbRRQmankq5jBUfvjtV88LynKfYpXZ) (link expires in 1 week)

In a grasp : `Failed initialize Steam service: ConnectToGlobalUser failed.` + the same `Failed loading game world '/content/worlds/default.deworld': Division by zero` as before

**Comment by LordOfDragons** [comment]
The Steam error is not a problem. It simply means Steam is not available so the module refuses to load. The problem is again this stupid div by zero which makes no sense. It's output to happen in
```
Dragengine.Gui.ProgressGauge.createBlendColorMatrix(): 306
```
but that's a simple color matrix where the division is guard with a DEMath.max(x, 0.0001) call. I see no way for this to ever be 0 unless your distro somehow manages to inject a conflicting library into the engine. I've seen only one other strange crash situation in totally valid code and most probably the problem had been there also an incompatible library somewhere. But you are so far the only system I'm aware of which has this problem.

I'll try to see if I can reproduce something using a "Linux Mint 22.1" docker image. I'm sure the problem has to do with the distro somehow and not the GPU.

**Comment by lautriva** [comment]
The problem might not be related to the `createBlendColorMatrix()` but may be a side-effect of memory corruption in other part of code 🙂

If it helps, I'm on `Xfce` edition of Linux Mint (22.2 now, since update)

**Comment by LordOfDragons** [comment]
I ran now the docker image linuxmintd/mint22.2-amd64 with DEMoCap 1.6 and Drag[en]gine 1.29 and it worked without crashing or causing a div-by-zero. There has to be something special on your system causing this. I'm not sure though where to look for the problem. Granted a docker image is not 100% the same as a real system installation and it has pure X11 no Xfce nor KDE but I would not expect this to cause much of a difference.

Just a wild guess but could there be damaged system files or even a faulty RAM? Grabbing for straws here right now.
